apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Time displaying function.
  annotations:
     github.com/project-slug: neerajkheria/python-app
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: development
  lifecycle: experimental
